---
version: "2"
plugins:
  structure:
    enabled: false
  duplication:
    enabled: false
  gofmt:
    enabled: true
  golint:
    enabled: true
    checks:
      GoLint/Comments/DocComments:
        enabled: false
      GoLint/Naming/MixedCaps:
        enabled: false
      GoLint/Naming/PackageNames:
        enabled: false
  govet:
    enabled: true
  gocyclo:
    enabled: true
    config:
      over: 9
    exclude_patterns:
    - vendor/
    - helpers/shell_escape.go
    - executors/kubernetes/executor_kubernetes_test.go
    - executors/kubernetes/util_test.go
    - executors/kubernetes/exec_test.go
    - executors/parallels/
    - executors/virtualbox/
  fixme:
    enabled: false
  shellcheck:
    enabled: false
exclude_patterns:
- vendor/
